### ISSUE TITLE
Power consumption

### ISSUE THREAD

**Issue by SPEC1AL1ST** [syssi/xiaomi_airconditioningcompanion#123]
How can I see the power consumption?
The air conditioner is connected to the companion. The original app shows the power consumption.

**Comment by syssi** [comment]
Which acpartner model do you own?

**Comment by SPEC1AL1ST** [comment]
Aqara Air Conditioning Companion (lumi.acpartner.v3) and his have it...

**Comment by syssi** [comment]
Could you provide a screenshot of your `climate` entity (`dev-state` page of the developer tools). There should be an attribute called `load_power` providing the power consumption.

**Comment by dincojazz** [comment]
Hi!
I have the same problem...
Can you give me some advice for show up power consumption at lovelace card?
> The air conditioner is connected to the companion. The original Xiaomi Mi Home app shows the power consumption.
> Aqara Air Conditioning Companion (lumi.acpartner.v1) and his have it...
There are screenshots from Home Assistant:
![LovelaceCard](https://user-images.githubusercontent.com/75685324/123557218-5b32f880-d798-11eb-8288-7ade23f8667f.png)
![ClimateAqaraACC](https://user-images.githubusercontent.com/75685324/123557222-6128d980-d798-11eb-82d1-be6f49cc0938.png)

**Comment by zsqduke** [comment]
Hi, syssi
I found the load_power attribute and I was able to create a template sensor using it and then use Riemann sum integral to create an energy sensor. This gives me a power consumption but the number a little bit smaller than what Mi Home reports.

So here’s my request. Add the native power consumption (kWh) statistic to this integration, as an additional attribute. That would makes this plug-in perfect! I appreciate all your work!

**Comment by SPEC1AL1ST** [comment]
Still, the option is very necessary. Can anyone help implement it?

**Comment by syssi** [comment]
```
template:
  - sensor:
    unique_id: "sensor"
      - name: "acpartner load power attribute as sensor"
        state: "{{ state_attr('climate.YOUR_ACPARNTER_ENTITY', 'load_power') }}"
        unit_of_measurement: W
```

The sensor provides the measurements of the acpartner 1:1 (instantaneous power in `W`). If you are looking for the power consumption in `Wh` you have to calculate the integral:

```
sensor:
  - platform: integration
    name: "acpartner power consumption"
    round: 6
    unit_time: h
    source: sensor.acpartner_load_power_attribute_as_sensor
```
