### ISSUE TITLE
KTBL02LM (acaprtner.v2) new firmware enable "wireless comunication protocol"

### ISSUE THREAD

**Issue by enrysan0** [syssi/xiaomi_airconditioningcompanion#36]
Hi,

as mentioned in the title the last firmware upgrade of the round "Xiaomi Mi Air Conditioner Companion" just enabled the wireless comunication protocol.

<a href="https://ibb.co/eJAehz"><img src="https://thumb.ibb.co/eJAehz/Screen_Shot_2018_09_06_at_18_30_54.png" alt="Screen_Shot_2018_09_06_at_18_30_54" border="0"></a>

<a href="https://ibb.co/fALn2z"><img src="https://thumb.ibb.co/fALn2z/Screen_Shot_2018_09_06_at_18_39_37.png" alt="Screen_Shot_2018_09_06_at_18_39_37" border="0"></a>

How can we use that with HomeAssistant? just for the Hub part or also for the AC/IR remote part?

Thanks

**Comment by syssi** [comment]
I've enable the "wireless communication protocol":

- 3 dots at the top right corner -> Use help -> About -> tab "Plug-in-version: 2.65.9" multiple times
- A new menu item appears: "Wireless communication protocol"
- Go to the new item, turn the "Wireless communication protocol" *on*
- Press OK 
- A message appaers: "Operation succeeded"

In the past the last step has failed. Unfortunately the protocol isn't available/activated anyway. It can be checked by:

```
$ nmap -sU -p 9898 192.168.130.83

Starting Nmap 7.40 ( https://nmap.org ) at 2018-11-17 10:05 CET
Nmap scan report for lumi-acpartner-v1-miio54979480.fritz.box (192.168.130.83)
Host is up (0.039s latency).
PORT     STATE  SERVICE
9898/udp closed monkeycom
MAC Address: 28:6C:07:F0:EC:29 (Xiaomi Electronics,co.)

Nmap done: 1 IP address (1 host up) scanned in 1.00 seconds

$ nc -v -uz 192.168.130.83 9898
lumi-acpartner-v1-miio54979480 [192.168.130.83] 9898 (?) : Connection refused

```

The port 9898 should be open and a connection should be possible. This is the proper feedback of a lumi gateway v3:

```
$ nmap -sU -p 9898 192.168.130.29
Starting Nmap 7.40 ( https://nmap.org ) at 2018-11-17 10:12 CET
Nmap scan report for lumi-gateway-v3-miio52244965.fritz.box (192.168.130.29)
Host is up (0.12s latency).
PORT     STATE SERVICE
9898/udp open  monkeycom
MAC Address: 28:6C:07:88:B3:60 (Xiaomi Electronics,co.)

Nmap done: 1 IP address (1 host up) scanned in 0.97 seconds

$ nc -v -uz 192.168.130.29 9898
lumi-gateway-v3-miio52244965 [192.168.130.29] 9898 (?) open
```

**Comment by syssi** [comment]
Oh, sorry. I just realized I own a acpartner.v1. The latest firmware version is called 1.4.1_152.0143 here and doesn't provide proper LAN protocol support right now.

Try to use the xiaomi_aqara component (of HA) to access your acpartner.v2:

```
logger:                                                                                                                                                                                                                                        
  default: warn                                                                                                                                                                                                                                
  logs:                                                                                                                                                                                                                                        
    homeassistant.components.xiaomi_aqara.binary_sensor: debug                                                                                                                                                                                
    homeassistant.components.xiaomi_aqara: debug                                                                                                                                                                                              
    xiaomi_gateway: debug

xiaomi_aqara:
  gateways:
    - mac: 286c0ffffffff
      key: vf1ddddddddddddd
```

Could you provide the content of your home-assistant.log?
