### ISSUE TITLE
Cannot capture infrared command

### ISSUE THREAD

**Issue by syhmosh** [syssi/xiaomi_airconditioningcompanion#38]
Hass version 0.77.3
when i was calling `climate.xiaomi_miio_learn_command` without any arguments,
i could only get an error: `[custom_components.climate.xiaomi_miio] Timeout. No infrared command captured`,  although i pressed the remote control for several times

**Comment by wzwick** [comment]
did you find an answer to this? I have the same issue

**Comment by syssi** [comment]
Which hardware version do you use/own? Did you test different remote controls? There are some remote controls which aren't supported / cannot be captured.

**Comment by wzwick** [comment]
The square companion, I think it's lumipartner3 or something like that.
Yes tested different remotes, same thing -times out with no capture.
I have since bought the Xiaomi ir remote and that captures fine (it's now a non issue for me)
Do you know the config to send a command from the Aircon companion?

**Comment by syssi** [comment]
I've tested the feature with an acpartner.v2. It looks like the implementation doesn't work for the v3. Are you willing to do some testing.

**Comment by wzwick** [comment]
For the greater good - most definitely.

**Comment by syhmosh** [comment]
I'm using an acpartner.v2 , here's the log `lumi.acpartner.v2 1.4.1_145 MW300 detected`.
Still it doesn't work for me, however it acts correctly in mijia app.

**Comment by syssi** [comment]
Could you try to capture infrared commands via python-miio directly:

```
miiocli airconditioningcompanion --ip IP --token TOKEN learn 1

# send an IR command
miiocli airconditioningcompanion --ip IP --token TOKEN learn_result
# send an IR command
miiocli airconditioningcompanion --ip IP --token TOKEN learn_result
# send an IR command
miiocli airconditioningcompanion --ip IP --token TOKEN learn_result

miiocli airconditioningcompanion --ip IP --token TOKEN learn_stop 1
```

Does it work?

**Comment by syhmosh** [comment]
Not work ...
![default](https://user-images.githubusercontent.com/3928569/48780669-69355880-ed15-11e8-8ef6-39f6755eb84f.png)
And I update python-miio from 0.41 to 0.43, nothing changed...

**Comment by syssi** [comment]
Please try again with:

```
miiocli airconditioningcompanion --ip IP --token TOKEN raw_command start_ir_learn "[1]"
miiocli airconditioningcompanion --ip IP --token TOKEN raw_command get_ir_learn_result "[]"
miiocli airconditioningcompanion --ip IP --token TOKEN raw_command get_ir_learn_result "[]"
miiocli airconditioningcompanion --ip IP --token TOKEN raw_command get_ir_learn_result "[]"
```

cp. https://github.com/syssi/xiaomi_airconditioningcompanion/issues/5#issuecomment-371224218

**Comment by syhmosh** [comment]
Still not work...  
Still null for this command...

**Comment by syssi** [comment]
Okay. Slot 1 is the problem. Please try:

```
miiocli airconditioningcompanion --ip IP --token TOKEN learn 15

# send an IR command
miiocli airconditioningcompanion --ip IP --token TOKEN learn_result
# send an IR command
miiocli airconditioningcompanion --ip IP --token TOKEN learn_result
# send an IR command
miiocli airconditioningcompanion --ip IP --token TOKEN learn_result

miiocli airconditioningcompanion --ip IP --token TOKEN learn_stop 15
```

**Comment by syhmosh** [comment]
You're awesome.
Deepest thanks to you!

**Comment by wzwick** [comment]
@syssi Could you please help me with the basic HA config to fire off a ir signal from the airconcompanion?
I have the following:

```
 - platform: xiaomi_miio
    name: Air Controller
    host: 192.168.xxx.xxx
    token: f4c087xxxxxxxxxxxxxxxxxxcedd0831
    target_sensor: sensor.temperature_zigbee
    scan_interval: 60
    commands:
      tv_power:
        command:
          - raw:Z6VPAP0BAABdAgAAtwYAANkIAACTEQAAySIAAMSfAAAMdQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABFEBAQEBAQEBAgICAgICAQICAQICAQEBAQECAQECAgICBgNXA1cDUA
```

then i use a script:
```
'test':
  alias: test
  sequence:
    - service: climate.xiaomi_miio_send_command
      entity_id: 'climate.air_controller'
      data:
        command:
          - 'tv_power'
```

the command works fine sending it from the xiaomi universal remote - but i cant seem to get it working from the air conditioner companion.
please assist
