### ISSUE TITLE
Platform not found: climate.xiaomi_miio_airconditioningcompanion

### ISSUE THREAD

**Issue by rddkrn** [syssi/xiaomi_airconditioningcompanion#52]
Hello, 
I made changes like the update that was given, but I have an error "Platform not found: climate.xiaomi_miio_airconditioningcompanion". Did I miss something?
Thank you very much.

**Comment by leungyuan** [comment]
> Hello,
> I made changes like the update that was given, but I have an error "Platform not found: climate.xiaomi_miio_airconditioningcompanion". Did I miss something?
> Thank you very much.
Hope you did not miss this:
`chmod +x <configuration_path>/custom_components/xiaomi_airconditioningcompanion/climate.py`

**Comment by hsie** [comment]
thanks and just wonder if the files structure of your component for the switch would also be adjusted accordingly?

https://github.com/syssi/xiaomiplug

**Comment by rddkrn** [comment]
> > Hello,
> > I made changes like the update that was given, but I have an error "Platform not found: climate.xiaomi_miio_airconditioningcompanion". Did I miss something?
> > Thank you very much.
> 
> Hope you did not miss this:
> `chmod +x <configuration_path>/custom_components/xiaomi_airconditioningcompanion/climate.py`

I am already created the folder and file. But still same result. Is there configuration that I should change. I am running Hass.io on Raspi.
Thanks.

**Comment by flexyneat** [comment]
I've made the necessary changes, but i still keep getting the error that platform does not exist

**Comment by syssi** [comment]
@flexyneat Please provide your configuration and a directory listing of your custom_components directory. It should look like this:

```
# configuration.yaml
climate:
  - platform: xiaomi_miio_airconditioningcompanion
    name: Aqara Air Conditioning Companion
    host: 192.168.132.35
    token: 2a65c6b7d2351b9cda2ecfd6de6baf00
    target_sensor: input_number.temperature
    scan_interval: 60

input_number:
  temperature:
    name: Virtual temperature
    min: 10
    max: 28
    step: 0.5
    icon: mdi:thermometer
    unit_of_measurement: '°C'

logger:
  default: warn
  logs:
    custom_components.xiaomi_miio_airconditioningcompanion.climate: debug
    miio: debug
```

```
$ find .homeassistant -name *.py
.homeassistant/custom_components/xiaomi_miio_airconditioningcompanion/__init__.py
.homeassistant/custom_components/xiaomi_miio_airconditioningcompanion/climate.py
```
