### ISSUE TITLE
cant initiate component integration on configuration.yaml

### ISSUE THREAD

**Issue by chimneybear** [syssi/xiaomi_airconditioningcompanion#86]
I've added this repository https://github.com/syssi/xiaomi_airconditioningcompanion onto my hassio running on RPI3 - home assistant ver 0.100.2 

Here are the lines i added onto my configuration.yaml:
```
climate:
  - platform: xiaomi_miio_airconditioningcompanion
    name: Aqara Air Conditioning Companion
    host: 192.168.2.7
    token: !secret living_hub_key
    target_sensor: sensor.temp_living
    scan_interval: 60
```
Am getting this error when I check config:

> Platform error climate.xiaomi_miio_airconditioningcompanion - Integration 'xiaomi_miio_airconditioningcompanion' not found.

What went wrong?
