### ISSUE TITLE
Unable to add multiple air conditioning companions

### ISSUE THREAD

**Issue by unpack8866** [syssi/xiaomi_airconditioningcompanion#89]
Unable to add multiple air conditioning companions

**Comment by syssi** [comment]
What did you try? Could you provide your error log?

**Comment by syssi** [comment]
It should be possible without issues by:

```
climate:
  - platform: xiaomi_miio_airconditioningcompanion
    name: Aqara Air Conditioning Companion No 1
    host: 192.168.130.71
    token: FIRST_TOKEN
    target_sensor: sensor.temperature_bedroom
    scan_interval: 60
  - platform: xiaomi_miio_airconditioningcompanion
    name: Aqara Air Conditioning Companion No 2
    host: 192.168.130.72
    token: SECOND_TOKEN
    target_sensor: sensor.temperature_livingroom
    scan_interval: 60
```
